SpotifyWeb.Mvc/SpotifyWeb.Mvc/Controllers/AlbumsController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using SpotifyWeb.Mvc.Service.Helpers;
using SpotifyWeb.Mvc.Model;
using SpotifyWeb.Mvc.Service;
using SpotifyWeb.Mvc.ViewModel;

namespace Spotify.Web.Mvc.Controllers
{
    public class AlbumsController : Controller
    {
        SpotifyService spotifyService = new SpotifyService();


        public ActionResult Index()
        {
            if (Session["token"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var token = Session["token"].ToString();

            // carrega os albums e preenche em uma sessão
            var albums = GetAllAlbums(token);
            albums = albums.DistinctBy(x => x.id).ToList();

            HttpContext.Session.Remove("albums");
            Session["albums"] = albums;

            return View();
        }

        public ActionResult GetData(int? page, int? pageSize)
        {
            if (Session["token"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var token = Session["token"].ToString();

            var albums = (List<Album>)Session["albums"];

            albums = albums.DistinctBy(x => x.id).ToList();

            var retorno = (from c in albums select c).Skip(page.Value * pageSize.Value).Take(pageSize.Value);

            return Json(retorno.ToList(), JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetAlbum(string albumId)
        {
            return RedirectToAction("AlbumDetails", new { albumId = albumId });
        }

        public ActionResult AlbumDetails(string albumId)
        {
            if (string.IsNullOrEmpty(Session["token"].ToString()))
            {
                return RedirectToAction("Index", "Home");
            }

            var token = Session["token"].ToString();

            var album = GetAlbumWithTracks(albumId, token);

            List<Track> tracks = new List<Track>();
            List<string> timesDurations = new List<string>();

            foreach (var trk in album.tracks.items)
            {
                Track track = new Track
                {
                    name = trk.name,
                    track_number = trk.track_number,
                    track_duration_formatted = SpotifyHelpers.TrackDurationFormatted(trk.duration_ms.ToString()),
                    explicito = trk.explicito
                };

                tracks.Add(track);
                timesDurations.Add(trk.duration_ms.ToString());
            }

            AlbumDetailsViewModel vm = new AlbumDetailsViewModel
            {
                AlbumName = album.name,
                ArtistName = album.artists[0].name,
                ImageUrl = album.images[0].url,
                Copyrights = album.copyrights,
                TracksCount = album.tracks.items.Count,
                ReleaseDate = string.IsNullOrEmpty(album.release_date) ? "" : album.release_date.Substring(0, 4),
                ExtendedDuration = SpotifyHelpers.TrackDurationFormatted_2(timesDurations),
                Tracks = tracks
            };

            return View(vm);
        }


        #region Album Information
        public ActionResult Album(string albumId)
        {
            return RedirectToAction("GetSavedAlbumDetails", new { albumId = albumId });
        }
        #endregion

        #region Saved Albums        
        public ActionResult SavedAlbums()
        {
            return View();
        }
        public ActionResult GetSavedAlbums(int? page, int? pageSize)
        {
            if (Session["token"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var token = Session["token"].ToString();

            int limit = pageSize.Value;
            int offset = (page.Value * pageSize.Value);

            var savedAlbumsList = spotifyService.GetSavedAlbums(token, limit, offset);

            return Json(savedAlbumsList.items.ToList(), JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetSavedAlbumDetails(string albumId)
        {
            if (Session["token"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var token = Session["token"].ToString();
            var album = spotifyService.GetAlbum(token, albumId);

            return View("SavedAlbumDetails", album);
        }
        #endregion

        private List<Album> GetAllAlbums(string token)
        {
            if (token == null)
                return null;

            List<Album> albums = new List<Album>();

            UserProfiles spotifyUser = spotifyService.GetCurrentUserProfile(token);
            List<Playlist> userPlaylists = spotifyService.GetUserPlaylists(token, spotifyUser.id, 50, 0);
            List<PlaylistTrackItem> tracks = new List<PlaylistTrackItem>();

            foreach (var playlist in userPlaylists)
            {
                var tracksFromPlaylist = GetTracksFromPlaylist(token, playlist, spotifyUser);

                foreach (var track in tracksFromPlaylist)
                {
                    var album = track.track.album;
                    albums.Add(album);
                }


                foreach (var t in tracksFromPlaylist)
                {
                    tracks.Add(t);
                }
            }

            Session["Tracks"] = tracks;

            return albums;
        }

        private Album GetAlbumWithTracks(string albumId, string token)
        {
            if (token == null)
                return null;

            // Recupera as musicas das playlists -------------------------------------------------------------------------
            UserProfiles spotifyUser = spotifyService.GetCurrentUserProfile(token);
            List<Playlist> userPlaylists = spotifyService.GetUserPlaylists(token, spotifyUser.id, 50, 0);

            List<PlaylistTrackItem> tracksList = new List<PlaylistTrackItem>();
            tracksList = (List<PlaylistTrackItem>)Session["Tracks"];
            //------------------------------------------------------------------------------------------------------------

            var sessionAlbums = (List<Album>)Session["albums"];

            var album = spotifyService.GetAlbum(token, albumId);

            Tracks t = new Tracks();
            List<Track> it = new List<Track>();

            foreach (var trackAlbum in album.tracks.items)
            {
                foreach (var trackList in tracksList)
                {
                    if (trackAlbum.id == trackList.track.id)
                    {
                        it.Add(trackAlbum);
                    }
                }
            }

            //Limpa as musicas do album
            album.tracks.items.Clear();

            // adiciona as musicas que são do usuário e pertencem ao album
            t.items = it;
            album.tracks = t;

            return album;
        }

        private List<PlaylistTrackItem> GetTracksFromPlaylist(string token, Playlist playlist, UserProfiles spotifyUser)
        {
            // Adicionando a primeira consulta na lista -----------------------------------------------------------------------
            List<PlaylistTrackItem> listTracks = new List<PlaylistTrackItem>();

            int totalTracks = playlist.tracks.total;
            int limit = 50;
            int offset = 0;

            var tracksFromPlaylist = spotifyService.GetPlaylistTracks(token, spotifyUser.id, playlist.id, limit, offset);

            foreach (var track in tracksFromPlaylist)
            {
                listTracks.Add(track);
            }

            int index = offset + 1;
            offset = limit * index;
            //-----------------------------------------------------------------------------------------------------------------

            if (tracksFromPlaylist.Count > 0)
            {
                // demais consultas ao metodo ------------------------------------------------------------------------------------
                for (int i = 0; i < totalTracks; i++)
                {
                    if (!(offset > totalTracks))
                    {
                        var tracksFromPlaylistOnLoop = spotifyService.GetPlaylistTracks(token, spotifyUser.id, playlist.id, limit, offset);

                        foreach (var track in tracksFromPlaylistOnLoop)
                        {
                            listTracks.Add(track);
                        }

                        index = index + 1;
                        offset = limit * index;
                    }
                }
                //-----------------------------------------------------------------------------------------------------------------                                                
            }

            return listTracks;
        }

    }
}

SpotifyWeb.Mvc/SpotifyWeb.Mvc/Controllers/TracksController.cs
using System.Linq;
using System.Web.Mvc;
using SpotifyWeb.Mvc.Service;

namespace Spotify.Web.Mvc.Controllers
{
    public class TracksController : Controller
    {
        SpotifyService spotifyService = new SpotifyService();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetData(int? page, int? pageSize)
        {
            if (Session["token"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var token = Session["token"].ToString();

            int limit = pageSize.Value;
            int offset = (page.Value * pageSize.Value);

            var savedTracksList = spotifyService.GetSavedTracks(token, limit, offset);

            return Json(savedTracksList.items.ToList(), JsonRequestBehavior.AllowGet);
        }
    }
}

SpotifyWeb.Mvc/SpotifyWeb.Mvc/Views/Tracks/Index.cshtml
@{
    ViewBag.Title = "Songs";
}

<style>

    .link { text-decoration: none; color: #2e2f33; }
    .link a:hover, a:focus { text-decoration: underline; font-weight: bold !important; color: #2e2f33 !important; }


</style>

@section scripts {
    
    <script type="text/javascript">

        var page = 0;
        var pageSize = 20;
        var _inCallback = false;

        $(function () {
            LoadData();
        });

        $(window).scroll(function () {
            if ($(window).scrollTop() == $(document).height() - $(window).height()) {

                LoadData();
            }
        });

        function LoadData() {
            if (page > -1 && !_inCallback) {
                _inCallback = true;

                $.ajax({
                    type: 'GET',
                    url: '/Tracks/GetData',
                    data: {
                        "page": page,
                        "pageSize": pageSize
                    },
                    dataType: 'json',
                    success: function (response) {
                        if (response == null || !response.length > 0) {
                            page = -1;
                            return;
                        }

                        var tableHtml = createTableFromData(response);
                        $(tableHtml).appendTo("#result");
                        _inCallback = false;
                        page++;
                    },
                    beforeSend: function () {
                        $("#loading").show();
                    },
                    complete: function () {
                        $("#loading").hide();
                    },
                    error: function () {
                        alert('Error while retrieving data from Spotify Api');
                    }
                });
            }
        }


        function createTableFromData(response) {

            var tableHtml = "";
            
            for (var i = 0; i < response.length; i++) {

                var urlToArtist = '@Url.Action("GetArtist", "Artists")?artistId=' + response[i].track.artists[0].id;
                var urlToAlbum = '@Url.Action("GetAlbum", "Albums")?albumId=' + response[i].track.album.id;

                tableHtml += "<tr>";
                tableHtml += "  <td>" + response[i].track.name.substring(0, 38) + "</td>";

                if (response[i].track.explicito) {
                    tableHtml += "  <td><span class='custom-label label-transparent' style='font-size: 7pt !important'>EXPLICIT</span></td>";
                }
                else {
                    tableHtml += "  <td>&nbsp;</td>";
                }

                tableHtml += "  <td><a href= '" + urlToArtist + "' class='link'>" + response[i].track.artists[0].name + "</a></td>";
                tableHtml += "  <td><a href= '" + urlToAlbum + "' class='link'>" + response[i].track.album.name + "</a></td>";
                tableHtml += "  <td>" + convertDateTime(response[i].added_at) + "</td>";
                tableHtml += "  <td>" + formattDurationTrack(response[i].track.duration_ms) + "</td>";
                tableHtml += "</tr>";
            }

            return tableHtml;
        }

        String.format = function () {
            var s = arguments[0];
            for (var i = 0; i < arguments.length - 1; i++) {
                var reg = new RegExp("\\{" + i + "\\}", "gm");
                s = s.replace(reg, arguments[i + 1]);
            }
            return s;
        }


        function convertDateTime(value) {
            if (value === null)
                return null;

            var date = value.substring(0, 10);

            var dateSplit = date.split('-');

            return String.format("{0}-{1}-{2}", dateSplit[2], dateSplit[1], dateSplit[0]);
        }

        function formattDurationTrack(millisec) {
            var seconds = (millisec / 1000).toFixed(0);
            var minutes = Math.floor(seconds / 60);
            var hours = "";

            if (minutes > 59) {
                hours = Math.floor(minutes / 60);
                hours = (hours >= 10) ? hours : "0" + hours;
                minutes = minutes - (hours * 60);
                minutes = (minutes >= 10) ? minutes : "0" + minutes;
            }

            seconds = Math.floor(seconds % 60);
            seconds = (seconds >= 10) ? seconds : "0" + seconds;

            if (hours != "") {
                return hours + ":" + minutes + ":" + seconds;
            }

            return minutes + ":" + seconds;

        }

    </script>    
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Songs</h1>
    </div>
</div>

<div class="row">
    <table class="table" style="border-bottom: 1px solid #ccc;">
        <thead>
            <tr>
                <th>SONG</th>
                <th></th>
                <th>ARTIST</th>
                <th>ALBUM</th>
                <th>
                    <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
                </th>
                <th>
                    <span class="glyphicon glyphicon-time" aria-hidden="true"></span>
                </th>
            </tr>
        </thead>
        <tbody id="result"></tbody>
    </table>
</div>


<div class="row" style="display:none; padding-top: 30px; padding-bottom: 30px" id="loading">
    <div class="col-sm-12">
        <div class="text-center">
            Por favor, aguarde...<br />
            <img src="~/images/ajax-loader.gif" />
        </div>
    </div>
</div>