SpotifyWeb.Mvc/SpotifyWeb.Mvc/Controllers/ArtistsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using SpotifyWeb.Mvc.Service.Helpers;
using SpotifyWeb.Mvc.Model;
using SpotifyWeb.Mvc.Service;

namespace Spotify.Web.Mvc.Controllers
{
    public class ArtistsController : Controller
    {
        SpotifyService spotifyService = new SpotifyService();

        // GET: Artists
        public ActionResult Index()
        {
            if (Session["token"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var token = Session["token"].ToString();

            var artists = GetAllArtists(token);

            HttpContext.Session.Remove("artists");
            Session["artists"] = artists;

            return View();
        }


        public ActionResult GetData(int? page, int? pageSize)
        {
            if (Session["token"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var artists = (List<ItemArtist>)Session["artists"];

            var retorno = (from c in artists select c)
                          .Skip(page.Value * pageSize.Value)
                          .Take(pageSize.Value);

            return Json(retorno.ToList(), JsonRequestBehavior.AllowGet);
        }

        // Retorna todos os artistas das playlists
        private List<ItemArtist> GetAllArtists(string token)
        {
            if (token == null)
                return null;

            List<ItemArtist> artists = new List<ItemArtist>();
            List<ItemArtist> artistsAux = new List<ItemArtist>();
            //Artists artistsAux = new Artists();

            List<string> ids_artists = new List<string>();

            UserProfiles spotifyUser = spotifyService.GetCurrentUserProfile(token);
            List<Playlist> userPlaylists = spotifyService.GetUserPlaylists(token, spotifyUser.id, 50, 0);
            List<PlaylistTrackItem> tracks = new List<PlaylistTrackItem>();

            // Para cada playlist do usuário, obtem as musicas
            foreach (var playlist in userPlaylists)
            {
                var tracksFromPlaylist = GetTracksFromPlaylist(token, playlist, spotifyUser);

                // Para cada musica das playlists, armazena o id do artista na lista
                foreach (var track in tracksFromPlaylist)
                {
                    var id = track.track.artists[0].id;
                    ids_artists.Add(id);
                }
            }

            //Obtem os artistas seguidos
            var followedArtists = GetFollowedArtists(token);

            foreach (var artistFollowed in followedArtists.items)
            {
                var id = artistFollowed.id;
                ids_artists.Add(id);
            }

            // Apenas ids DISTINTOS
            ids_artists = ids_artists.Distinct().ToList();

            int qtdeIds = ids_artists.Count;
            int maximumIds = 50;
            int qtdePartes = Convert.ToInt32(Math.Ceiling(Convert.ToDouble(qtdeIds) / Convert.ToDouble(maximumIds)));

            var idsSeparadosEmPartes = SpotifyHelpers.SplitList<string>(ids_artists, qtdePartes);

            IEnumerable<string>[] partesDosIds = new IEnumerable<string>[qtdePartes];

            //Obtem os artistas das playlists
            for (int i = 0; i < idsSeparadosEmPartes.Count(); i++)
            {
                partesDosIds[i] = idsSeparadosEmPartes.ElementAt(i);
                artistsAux = spotifyService.GetSeveralArtists(token, partesDosIds[i].ToList());
                artistsAux.ForEach(c => artists.Add(c));
            }

            return artists;
        }

        // Retorna os artistas seguidos pelo usuário
        private Artists GetFollowedArtists(string token)
        {
            var followedArtists = spotifyService.GetFollowedArtists(token);

            return followedArtists.artists;
        }

        // Retorna as musicas de todas as playlists do usuário
        private List<PlaylistTrackItem> GetTracksFromPlaylist(string token, Playlist playlist, UserProfiles spotifyUser)
        {
            // Adicionando a primeira consulta na lista -----------------------------------------------------------------------
            List<PlaylistTrackItem> listTracks = new List<PlaylistTrackItem>();

            int totalTracks = playlist.tracks.total;
            int limit = 50;
            int offset = 0;

            var tracksFromPlaylist = spotifyService.GetPlaylistTracks(token, spotifyUser.id, playlist.id, limit, offset);

            foreach (var track in tracksFromPlaylist)
            {
                listTracks.Add(track);
            }

            int index = offset + 1;
            offset = limit * index;
            //-----------------------------------------------------------------------------------------------------------------

            if (tracksFromPlaylist.Count > 0)
            {
                // demais consultas ao metodo ------------------------------------------------------------------------------------
                for (int i = 0; i < totalTracks; i++)
                {
                    if (!(offset > totalTracks))
                    {
                        var tracksFromPlaylistOnLoop = spotifyService.GetPlaylistTracks(token, spotifyUser.id, playlist.id, limit, offset);

                        foreach (var track in tracksFromPlaylistOnLoop)
                        {
                            listTracks.Add(track);
                        }

                        index = index + 1;
                        offset = limit * index;
                    }
                }
                //-----------------------------------------------------------------------------------------------------------------                                                
            }

            return listTracks;
        }



        #region Detalhes do Artista        
        public ActionResult ArtistDetails(string artistId)
        {
            if (Session["token"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var token = Session["token"].ToString();
            Session["artistId"] = artistId;

            //var artist = GetArtist(token, artistId);
            //var albums = GetArtistAlbums(token, artistId);
            //var popular = GetPopularTracks(token, artistId);
            //var related = GetRelatedArtists(token, artistId);
            //var singles = GetArtistSingles(token, artistId);
            //var appearsOn = GetArtistAppearsOn(token, artistId);
            //var compilations = GetArtistCompilations(token, artistId);

            //ArtistDetailsViewModel vm = new ArtistDetailsViewModel
            //{
            //    Artist = artist,
            //    ArtistAlbums = albums,
            //    ArtistSingles = singles,
            //    ArtistAppearsOn = appearsOn,
            //    ArtistCompilation = compilations,
            //    ArtistTopTracks = popular,
            //    RelatedArtists = related
            //};

            //return View(vm);
            return View();
        }

        public ActionResult GetArtist()
        {
            if (Session["token"] == null)
                return null;

            var token = Session["token"].ToString();
            var artistId = Session["artistId"].ToString();

            var artist = spotifyService.GetArtist(token, artistId);

            return Json(artist, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetPopularTracks()
        {
            if (Session["token"] == null)
                return null;

            var token = Session["token"].ToString();
            var artistId = Session["artistId"].ToString();

            var popularTracks = spotifyService.GetArtistTopTracks(token, artistId);

            return Json(popularTracks, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetRelatedArtists()
        {
            if (Session["token"] == null)
                return null;

            var token = Session["token"].ToString();
            var artistId = Session["artistId"].ToString();

            var relatedArtists = spotifyService.GetRelatedArtists(token, artistId);

            return Json(relatedArtists, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetArtistAlbums(int? page, int? pageSize)
        {
            if (Session["token"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var token = Session["token"].ToString();
            var artistId = Session["artistId"].ToString();

            int limit = pageSize.Value;
            int offset = (page.Value * pageSize.Value);

            var albums = spotifyService.GetArtistAlbums(token, artistId, limit, offset);

            if (!(albums.items.Count > 0))
                return Json(new { Message = "Fim" }, JsonRequestBehavior.AllowGet);

            var ids_albums = new List<string>();
            albums.items.ForEach(c => ids_albums.Add(c.id));

            // Apenas ids DISTINTOS
            ids_albums = ids_albums.Distinct().ToList();

            var albumsCompletos = spotifyService.GetSeveralAlbums(token, ids_albums);

            albumsCompletos = albumsCompletos.GroupBy(c => c.name).Select(g => g.First()).ToList();

            return Json(albumsCompletos.ToList(), JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetArtistSingles(int? page, int? pageSize)
        {
            if (Session["token"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var token = Session["token"].ToString();
            var artistId = Session["artistId"].ToString();

            int limit = pageSize.Value;
            int offset = (page.Value * pageSize.Value);

            var albums = spotifyService.GetArtistSingles(token, artistId, limit, offset);

SpotifyWeb.Mvc/SpotifyWeb.Mvc/Views/Artists/Index.cshtml
@{
    ViewBag.Title = "Artistas";
}
<style>

.img-center {
	margin: 0 auto;
}

.thumbnail {
        border: 0px solid #ddd !important;
    }
</style>


@section scripts {
    <script type="text/javascript">

        var page = 0;
        var pageSize = 8;
        var _inCallback = false;

        $(function () {
            LoadData();
        });

        $(window).scroll(function () {
            if ($(window).scrollTop() == $(document).height() - $(window).height()) {
                LoadData();
            }
        });

        function LoadData() {
            if (page > -1 && !_inCallback) {

                _inCallback = true;

                $.ajax({
                    type: 'GET',
                    url: '/Artists/GetData',
                    data: {
                        "page": page,
                        "pageSize": pageSize
                    },
                    dataType: 'json',
                    success: function (response) {
                        if (response == null || !response.length > 0) {
                            page = -1;
                            return;
                        }

                        var tableHtml = createTableFromData(response);
                        $(tableHtml).appendTo("#divResult");
                        _inCallback = false;
                        page++;
                    },
                    beforeSend: function () {
                        $("#loading").show();
                    },
                    complete: function () {
                        $("#loading").hide();
                    },
                    error: function () {
                        alert('Error while retrieving data from Spotify Api');
                    }
                });
            }
        }

        function createTableFromData(response) {
            var tableHtml = "";

            for (var i = 0; i < response.length; i++) {

                var url = '@Url.Action("ArtistDetails", "Artists")?artistId=' + response[i].id;

                tableHtml += "<div class='col-sm-6 col-md-3' style='width:285px !important; height:360px !important'>";
                tableHtml += "   <div class='thumbnail'>";
                tableHtml += "      <a href='" + url + "' class='linkArtist'>";
                tableHtml += "         <img class='img-responsive' src='" + response[i].images[0].url + "' alt='" + response[i].name + "' width='252' height='252' style='height: 250px !important;'>";
                tableHtml += "         <input type='hidden' id='hdnArtistId' value='" + response[i].id + "' />";
                tableHtml += "      </a>";
                tableHtml += "   </div>";
                tableHtml += "   <div class='caption' style='padding-left: 9px;'>";
                tableHtml += "      <h5>" + response[i].name + "</h5>";
                tableHtml += "      <p>";
                tableHtml += "         <span style='font-size:9pt; color:#708090'>" + formattedNumbers(response[i].followers.total.toString()) + " followers</span>";
                tableHtml += "      </p>";
                tableHtml += "   </div>";
                tableHtml += "</div>";
            }
            return tableHtml;
        }

        function formattedNumbers(value) {
            if (value === null)
                return null;

            var retorno = "";

            var tamanho = parseInt(value.length);
            
            switch (tamanho) {
                case 1: retorno = value; break;
                case 2: retorno = value; break;
                case 3: retorno = value; break;
                case 4: retorno = String.format("{0}.{1}", value.substring(0, tamanho - 3), value.substring(1, 4)); break;
                case 5: retorno = String.format("{0}.{1}", value.substring(0, tamanho - 3), value.substring(2, 5)); break;
                case 6: retorno = String.format("{0}.{1}", value.substring(0, tamanho - 3), value.substring(3, 6)); break;
                case 7: retorno = String.format("{0}.{1}.{2}", value.substring(0, tamanho - 6), value.substring(1, 4), value.substring(4, 7)); break;
                case 8: retorno = String.format("{0}.{1}.{2}", value.substring(0, tamanho - 6), value.substring(2, 5), value.substring(5, 8)); break;
                case 9: retorno = String.format("{0}.{1}.{2}", value.substring(0, tamanho - 6), value.substring(3, 6), value.substring(6, 9)); break;
                case 10: retorno = String.format("{0}.{1}.{2}.{3}", value.substring(0, tamanho - 9), value.substring(1, 4), value.substring(4, 7), value.substring(7, 10)); break;
                case 11: retorno = String.format("{0}.{1}.{2}.{3}", value.substring(0, tamanho - 9), value.substring(2, 5), value.substring(5, 8), value.substring(8, 11)); break;
                case 12: retorno = String.format("{0}.{1}.{2}.{3}", value.substring(0, tamanho - 9), value.substring(3, 6), value.substring(6, 9), value.substring(9, 12)); break;
                case 13: retorno = String.format("{0}.{1}.{2}.{3}.{4}", value.substring(0, tamanho - 12), value.substring(1, 4), value.substring(4, 7), value.substring(7, 10), value.substring(10, 13)); break;
                default:
                    retorno = "Not formatted";
                    break;
            }

            return retorno;
        }

        String.format = function () {
            var s = arguments[0];
            for (var i = 0; i < arguments.length - 1; i++) {
                var reg = new RegExp("\\{" + i + "\\}", "gm");
                s = s.replace(reg, arguments[i + 1]);
            }
            return s;
        }
    </script>    
}

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Artists</h1>
    </div>
</div>

<div class="row" id="divResult"></div>


<div class="row" style="display:none" id="loading">
    <div class="col-sm-12">
        <div class="text-center">
            <img src="~/images/ajax-loader.gif" />
        </div>
    </div>
</div>