SpotifyWeb.Mvc/SpotifyWeb.Mvc/Controllers/ProfileController.cs
using System.Web.Mvc;
using SpotifyWeb.Mvc.Service;
using SpotifyWeb.Mvc.Service.Helpers;

namespace SpotifyWeb.Mvc.Controllers
{
    public class ProfileController : Controller
    {
        SpotifyService spotifyService = new SpotifyService();

        // GET: Profile
        public ActionResult Index()
        {
            if (Session["token"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var token = Session["token"].ToString();
            var spotifyUser = spotifyService.GetCurrentUserProfile(token);

            ViewBag.Aniversario = SpotifyHelpers.FormattedBirthdate(spotifyUser.birthdate);
            ViewBag.Pais = SpotifyHelpers.GetCountryName(spotifyUser.country);

            return View(spotifyUser);
        }
    }
}

SpotifyWeb.Mvc/SpotifyWeb.Mvc/Controllers/TracksController.cs
using System.Linq;
using System.Web.Mvc;
using SpotifyWeb.Mvc.Service;

namespace Spotify.Web.Mvc.Controllers
{
    public class TracksController : Controller
    {
        SpotifyService spotifyService = new SpotifyService();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult GetData(int? page, int? pageSize)
        {
            if (Session["token"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var token = Session["token"].ToString();

            int limit = pageSize.Value;
            int offset = (page.Value * pageSize.Value);

            var savedTracksList = spotifyService.GetSavedTracks(token, limit, offset);

            return Json(savedTracksList.items.ToList(), JsonRequestBehavior.AllowGet);
        }
    }
}

SpotifyWeb.Mvc/SpotifyWeb.Mvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My Spotify Library</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <link rel="shortcut icon" href="~/favicon.ico">

    <link href="~/css/font-awesome.min.css" rel="stylesheet" />    

    <script src="~/Scripts/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <style type="text/css">
        li.dropdown.current-user .dropdown-toggle { padding:10px 4px 7px 9px }
        li.dropdown.current-user .dropdown-menu li a { border-bottom:none!important }
        
        .navbar-user-img {
            border-radius: 50%;
            width: 34px;
            height: 34px;
            box-shadow: 0 0 5px 2px rgba(0,0,0,.1);
            vertical-align: middle;
        }

        .navbar-user-img, .navbar-user-text, .pagination>li {
            display: inline-block;
        }
    </style>
</head>

<body>

    <!-- Menu --> 
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="@Url.Action("Index", "Playlist")"></a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Albums", "Index", "Albums")</li>
                    <li>@Html.ActionLink("Artists", "Index", "Artists")</li>
                    <li>@Html.ActionLink("Songs", "Index", "Tracks")</li>
                    <li>@Html.ActionLink("Saved Albums", "SavedAlbums", "Albums")</li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <img src="@Session["UserImage"]" class="user-img img-circle navbar-user-img" alt="">
                            <span class="username">@Session["UserId"]</span>
                            <i class="fa fa-angle-down" aria-hidden="true"></i> 
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="@Url.Action("Index", "Profile")">
                                    Minha conta
                                </a>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>

    <!-- Conteudo da pagina -->
    <div class="container">
        @RenderBody()
    </div>

    <!-- Rodapé -->
    <footer class="footer">
        <div class="container" style="color: #919496; font-size: 12px; letter-spacing: 1px; line-height: 1.5em; word-spacing: 1px;">
            <p class="text-muted">
                <small class="copyright">© @DateTime.Now.Year - Data provided by Spotify Api</small>
            </p>
        </div>
    </footer>


    <!-- Referências Javascripts -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/customScripts")    
    @RenderSection("scripts", required: false)
</body>
</html>